{% set name = "bionc" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ipuch/bioNC/archive/{{ version }}.tar.gz
  sha256: 2530c91b7e3354e4def5473ba3ca514e31766570b5195b2bd1c8cd52c5d59243

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - packaging
    - casadi
    - ezc3d
    - plotly
    - bioviz
    - pyomeca
    - dill
    - biorbd
    - mesa-libgl-devel-cos7-x86_64


test:
  commands:
    - xvfb-run python -c "import bionc"  # [linux]
    - pip check
  imports:
    - bionc  # [not linux]
  requires:
    - pip

about:
  home: https://github.com/Ipuch/bioNC
  summary: Natural Coordinates with python for biomechanics
  description: |
    This repository contains the source code for the bioNC library, a python package for biomechanics and natural coordinates formalism. Inverse and Forward approach are implemented.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/Ipuch/bioNC

extra:
  recipe-maintainers:
    - ipuch
