{% set name = "bionc" %}
{% set version = "0.11.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ipuch/bioNC/archive/{{ version }}.tar.gz
  sha256: 87e490bd031c24a19d955e24c4ab32dde4922a28d635aa849bb44c95bb9e9ec2

build:
  number: 0
  noarch: python
  script: "python -m pip install . -vv"

requirements:
  host:
    - pip
    - hatchling
    - python >={{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy
    - packaging
    - casadi
    - ezc3d
    - plotly
    - bioviz
    - pyomeca
    - dill
    - biorbd
    - numba
    - pyorerun

test:
  commands:
    - xvfb-run python -c "import bionc"  # [linux]
    - pip check
  imports:
    - bionc  # [not linux]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Ipuch/bioNC
  summary: Natural Coordinates with python for biomechanics
  description: |
    This repository contains the source code for the bioNC library, a python package for biomechanics and natural coordinates formalism. Inverse and Forward approach are implemented.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/Ipuch/bioNC

extra:
  recipe-maintainers:
    - ipuch
