{% set name = "bionc" %}
{% set version = "0.7.0" %}
{% build_num = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ipuch/bioNC/archive/{{ version }}.tar.gz
  sha256: 35fbe8e88321e7990a05ff15f7c10ad0260683748832afaa3dfa357c4b12e2b9

build:
  number: {{ build_num }}
  string: py{{ py }}_h{{ PKG_HASH }}_{{ build_num }}
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy
    - packaging
    - casadi
    - ezc3d
    - plotly
    - bioviz
    - pyomeca
    - dill
    - biorbd
    - mesa-libgl-devel-cos7-x86_64
    

test:
  imports:
    - bionc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Ipuch/bioNC
  summary: Natural Coordinates with python for biomechanics
  description: |
    This repository contains the source code for the bioNC library, a python package for biomechanics and natural coordinates formalism. Inverse and Forward approach are implemented.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/Ipuch/bioNC

extra:
  recipe-maintainers:
    - ipuch
